#ifndef __TYPES_H
#define __TYPES_H

#define MODE_SIGN_NN_CHIFFRE 1
#define MODE_DECHIFFREMENT 2
#define MODE_AFFICHAGE_DECHIFFRE 3
#define MODE_GENERATION_CLES 4
#define MODE_TRANSFERT_CLES 5

#define TAILLE_HASH_MD5 16
#define TAILLE 20
#define PASSPHRASE "3eeac98df7e7a8ab1c0ebb0f9dfc1"


#endif
